### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by ciampo** [Atyantik/pwa-srcset-loader#2]
Is there any plan to upgrade this plugin to support Webpack 4?

**Comment by tirthbodawala** [comment]
Sure. Let me do that asap. We are actually busy upgrading pawjs to webpack 4 and had planned to do this later, but if you need it, we will prioritize this.

**Comment by ciampo** [comment]
Thanks a lot for the quick answer!

It's not super urgent, but it would be great to have webpack support in the next couple of weeks.
Do you think you'd be able to upgrade it by then?

Also, would it be worth to get in contact with the authors of srcset-loader?

**Comment by tirthbodawala** [comment]
I have started working on it, let me try to finish it by this week. If any problem we contact the authors as well :)

**Comment by ciampo** [comment]
Hey @tirthbodawala , any updates on Webpack 4 compatibility?

**Comment by tirthbodawala** [comment]
@ciampo Sorry it has been a while. pwa-srcset-loader now supports webpack v4.x Just upgraded it today.
