### ISSUE TITLE
Upgrade sharp dependency for windows

### ISSUE THREAD

**Issue by arseneoaa** [Atyantik/pwa-srcset-loader#3]
Hello,

The current sharp version referenced, 0.20.8 fails installing on windows (I am on 64 bits).
Reproduction steps:
    `mkdir test`
    `npm init`
    `npm i sharp@0.20.8`
     Errors
The latest sharp version does not have this issue.

This error is causing npm install of `react-pwa` to fail.

Thanks!

**Comment by tirthbodawala** [comment]
Thanks for pointing it out. Let me upgrade the package.
